Gracefully handle Git repos in system branches with missing config
Previously if there were repos present in the system branch that weren't
put there with `morph edit` or had lost their Morph-specific
configuration entries somehow you might see this error:

    ERROR: Command failed: git config -z morph.repository