Fix prototype of create_source_pool()
This fixes an issue in `morph list-artifacts` and probably other commands:

    ERROR: Command failed: morph list-artifacts --quiet file:///ws/master/git.baserock.org/baserock/baserock/definitions HEAD systems/build-system-armv7lhf-jetson.morph systems/weston-system-armv7lhf-jetson.morph systems/genivi-baseline-system-armv7lhf-jetson.morph
    Traceback (most recent call last):
    File "/usr/lib/python2.7/site-packages/cliapp/app.py", line 190, in _run
        self.process_args(args)
    File "/usr/lib/python2.7/site-packages/morphlib/app.py", line 290, in process_args
        cliapp.Application.process_args(self, args)
    File "/usr/lib/python2.7/site-packages/cliapp/app.py", line 539, in process_args
        method(args[1:])
    File "/usr/lib/python2.7/site-packages/morphlib/plugins/list_artifacts_plugin.py", line 67, in list_artifacts
        repo, ref, system_filename)
    File "/usr/lib/python2.7/site-packages/morphlib/plugins/list_artifacts_plugin.py", line 91, in list_artifacts_for_system
        status_cb=self.app.status)
    File "/usr/lib/python2.7/site-packages/morphlib/sourceresolver.py", line 641, in create_source_pool
        definitions_original_ref=original_ref)
    File "/usr/lib/python2.7/site-packages/morphlib/sourceresolver.py", line 583, in traverse_morphs
        definitions_absref, definitions_tree, visit)
    File "/usr/lib/python2.7/site-packages/morphlib/sourceresolver.py", line 408, in _process_definitions_with_children
        definitions_queue = collections.deque(system_filenames)
    TypeError: 'NoneType' object is not iterable

The issue is that the sourceresolver.create_source_pool() function did
not work correctly if passed a single filename. This was a regression from
commit 4cc75039a78bd8aef9ef464bc0eb6c3ff16809d0.

In order to have a logical function prototype, the create_source_pool()
function now only takes a list of systems, instead of taking either a
single system or a list.

Change-Id: I8f5ec8859a7e26d8107ed1c268fe925818d080a5