Swap repr() for str() in ref add errmsg
Old message:

ERROR: Adding ref
refs/heads/baserock/builds/review/javier_jard_n/foundation_core/d3401783ea054fc18ee56ccdb0030d0a
with commit 1c60a89a98c5ee532fefd363240b06870ada02f5 failed in git
repository located at /src/definitions: AppException()

New message:

ERROR: Adding ref
refs/heads/baserock/builds/review/javier_jard_n/foundation_core/d3401783ea054fc18ee56ccdb0030d0a
with commit 1c60a89a98c5ee532fefd363240b06870ada02f5 failed in git
repository located at /src/definitions: Command failed: git update-ref
refs/heads/baserock/builds/review/javier_jard_n/foundation_core/d3401783ea054fc18ee56ccdb0030d0a
1c60a89a98c5ee532fefd363240b06870ada02f5...

Change-Id: Idc6a47388f53d358b7dfc2c0f7fa82eefbc92630