Fix crash in handling of recursive submodules
It turns out I completely broke Morph's handling of recursive submodules
in commit 0855c357e74e6dd7a.

We didn't notice because nothing in the reference systems actually uses
recursive submodules. However, building the baserock/tlsa/mason2 branch
of definitions.git triggered the bug due to the
delta:python-packages/gitpython chunk, which contains
delta:python-packages/gitdb which in turn contains
delta:python-packages/smmap.

The error is this:

    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/cliapp/app.py", line 190, in _run
        self.process_args(args)
      File "/src/morph/morphlib/app.py", line 290, in process_args
        cliapp.Application.process_args(self, args)
      File "/usr/lib/python2.7/site-packages/cliapp/app.py", line 539, in process_args
        method(args[1:])
      File "/src/morph/morphlib/plugins/build_plugin.py", line 291, in build
        self._build(source_pool, filename, component_names=component_names)
      File "/src/morph/morphlib/plugins/build_plugin.py", line 316, in _build
        bc.build_in_order(component)
      File "/src/morph/morphlib/buildcommand.py", line 296, in build_in_order
        self.cache_or_build_source(s, build_env)
      File "/src/morph/morphlib/buildcommand.py", line 316, in cache_or_build_source
        self.build_source(source, build_env)
      File "/src/morph/morphlib/buildcommand.py", line 336, in build_source
        self.fetch_sources(source)
      File "/src/morph/morphlib/buildcommand.py", line 400, in fetch_sources
        self.lrc.ensure_submodules(source.repo, source.sha1)
      File "/src/morph/morphlib/localrepocache.py", line 308, in ensure_submodules
        if (submod.url, submod.commit) not in done:
    AttributeError: 'tuple' object has no attribute 'url'

This commit fixes the breakage and the baserock/tlsa/mason2 branch of
definitions.git now builds again.

Change-Id: Id24ac40f4670a60655e84953bcfd84d8f77e1da9