Fix crash in `morph distbuild` command
This was causing:

    UnboundLocalError: local variable 'original_ref' referenced before assignment

Change-Id: I46e4b5d527d9ac5480a3d1fe5e6d631f0b7279dc