Rework debugging information for failed builds
* Improve error messages and remove redundant information

* Stop displaying the containerised settings, as they are not very
  helpful to debug a build failure

* Display the error code

* Change system integration commands logging to consistent with build
  commands logging.

* Provide a log file in the staging directory for each chunk build
  failure or system integration failure.

* Provide a chroot script in the staging directory for each chunk build
  failure or system integration build failure.  This script allows the
  user to enter an environment similiar to the one where the build
  failed.

* Fix a bug where the system integration commands stdout was being
  omitted when these commands failed.

* Fix a bug where the error_message_for_containerised_commandline() was
  being called with an empty error message, as the stderr was being
  directed to stdout.

Chunk build failure output before the this change and change
I16ebe9ba4ac46fef82e37d0b3e05f42d14249de8:

    2015-08-03 15:55:21 [Build 258/267] [test] Running build-commands
    build failed
    # configure
    # # echo "configure-commands stdout"
    configure-commands stdout
    # # echo "configure-commands stderr" >&2
    configure-commands stderr
    # build
    # # echo "build commands stdout"
    build commands stdout
    # # echo "build commands stderr" >&2
    build commands stderr
    # # echo "some more sdout"
    echo "some more stderr" >&2
    echo $PATH
    foo

    some more sdout
    some more stderr
    /tools/bin:/usr/bin:/usr/lib/ccache:/sbin:/usr/sbin:/bin:/usr/bin
    sh: foo: not found
    ERROR: In staging area /src/tmp/failed/tmpglc5Sz: Command failed: sh -c
    'echo "some more sdout"
    echo "some more stderr" >&2
    echo $PATH
    foo
    ':
    Containerisation settings: {'binds': (('/src/cache/ccache/nano-tarball',
    '/src/tmp/staging/tmpglc5Sz/tmp/ccache'),), 'mount_proc': True,
    'mounts': (('dev/shm', 'tmpfs', 'none'),), 'writable_paths':
    ['/src/tmp/staging/tmpglc5Sz/test.build',
    '/src/tmp/staging/tmpglc5Sz/test.inst',
    '/src/tmp/staging/tmpglc5Sz/dev', '/src/tmp/staging/tmpglc5Sz/proc',
    '/src/tmp/staging/tmpglc5Sz/tmp'], 'root': '/src/tmp/staging/tmpglc5Sz',
    'cwd': '/test.build'}
    Error output:

    $>

Chunk build failure output after this change and change
I16ebe9ba4ac46fef82e37d0b3e05f42d14249de8:

    2015-08-03 15:53:59 [Build 258/267] [test] Running build-commands
    ### CONFIGURE-COMMANDS ###
    + echo configure-commands stdout
    configure-commands stdout
    + echo configure-commands stderr
    configure-commands stderr
    ### BUILD-COMMANDS ###
    + echo build commands stdout
    build commands stdout
    + echo build commands stderr
    build commands stderr
    + echo some more sdout
    some more sdout
    + echo some more stderr
    some more stderr
    + echo /tools/bin:/usr/bin:/usr/lib/ccache:/sbin:/usr/sbin:/bin:/usr/bin
    /tools/bin:/usr/bin:/usr/lib/ccache:/sbin:/usr/sbin:/bin:/usr/bin
    + foo
    sh: foo: not found

    ERROR: In staging area /src/tmp/staging/tmpjES5_2: build failed (exi
    t_code=127)
    $>

System integration build failure output before this change and change
I16ebe9ba4ac46fef82e37d0b3e05f42d14249de8:

    2015-08-03 15:58:25 [Build 267/267] [build-system-x86_64] Running the
    system integration commands
    2015-08-03 15:58:25 [Build 267/267] [build-system-x86_64] Error while
    running system integration commands
    2015-08-03 15:58:25 [Build 267/267] [build-system-x86_64] Error while
    building system
    ERROR: Command failed:
    baserock/system-integration/00-test-test-misc-0002:
    Containerisation settings: {'mounts': (('dev/shm', 'tmpfs', 'none'),
    ('tmp', 'tmpfs', 'none')), 'mount_proc': True, 'root':
    '/src/tmp/staging/tmpvpwB4l/build-system-x86_64.inst'}
    Error output:
    + foo
    baserock/system-integration/00-test-test-misc-0002: line 1: foo: not
    found

    $>

System integration build failure output after this change and change
I16ebe9ba4ac46fef82e37d0b3e05f42d14249de8:

    2015-08-03 16:00:06 [Build 267/267] [build-system-x86_64] Running the
    system integration commands
    + echo stdout
    stdout
    + echo stderr
    stderr
    + foo
    baserock/system-integration/00-test-test-misc-0002: line 1: foo: not
    found

    ERROR: In staging area /src/tmp/staging/tmpl9VNzf: system integration
    commands failed (exit_code=127)

    $>

Change-Id: Id992f707f69f3fa761b4c21e9904c4e5328e1c77