deploy: Tighten SSH connectivity check
I accidentally tried to deploy a Baserock upgrade to a Fedora cloud
machine. Every SSH command that Morph ran got the following output:

    Please login as the user "fedora" rather than the user "root".

The existing implementation of check_ssh_connectivity() didn't raise
an exception, leading to confusing errors further down.

The new implementation produces this error:

    ERROR: Unexpected output from remote machine: Please login as the
    user "fedora" rather than the user "root".

Change-Id: Ida5a82b25d759167aa842194b0d833d0565b4acf